services:
  # Servidor Web (Apache + PHP 8.3)
  web:
    build: .
    container_name: web
    user: "${UID}:${GID}"
    ports:
      - "${WEB_PORT_EXT}:${WEB_PORT}"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - NPM_CONFIG_CACHE=/tmp/.npm # pasta de cache do npm
    depends_on:
      - database

  # Banco de Dados (PostgreSQL)
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    ports:
      - "${DB_PORT_EXT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
