version: '3.8'

services:
  # Servidor Web (Apache + PHP 8.3)
  web:
    build: .
    container_name: app_web
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  # Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: app_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
